const products = [
  // Notebooks
  {
    name: "Classmate A4 Notebook - 200 Pages",
    description: "Premium quality A4 notebook with 200 ruled pages. Perfect for students and professionals. Features soft cover, smooth paper, and durable binding.",
    category: "Notebooks",
    brand: "Classmate",
    price: 120,
    comparePrice: 150,
    sku: "CLM-001",
    stock: 500,
    images: ["https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=400"],
    tags: ["notebook", "ruled", "A4", "classmate"],
    status: "active",
    featured: true,
    variants: [
      { type: "Pages", value: "200", price: 120 },
      { type: "Pages", value: "300", price: 180 }
    ]
  },
  {
    name: "Classmate A5 Notebook - 120 Pages",
    description: "Compact A5 notebook with 120 ruled pages. Ideal for quick notes and sketches. Features durable cover and premium paper quality.",
    category: "Notebooks",
    brand: "Classmate",
    price: 85,
    comparePrice: 100,
    sku: "CLM-002",
    stock: 400,
    images: ["https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400"],
    tags: ["notebook", "ruled", "A5", "classmate"],
    status: "active",
    featured: false
  },
  {
    name: "Navneet Long Notebook - 172 Pages",
    description: "Long format notebook with 172 pages. Perfect for school use. Features ruled pages and sturdy binding.",
    category: "Notebooks",
    brand: "Navneet",
    price: 75,
    comparePrice: 90,
    sku: "NAV-001",
    stock: 600,
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400"],
    tags: ["notebook", "ruled", "long", "navneet"],
    status: "active",
    featured: true
  },
  {
    name: "Navneet Practical Notebook - 100 Pages",
    description: "Practical notebook with 100 pages. Ideal for lab work and practical subjects. Features plain pages.",
    category: "Notebooks",
    brand: "Navneet",
    price: 55,
    comparePrice: 70,
    sku: "NAV-002",
    stock: 350,
    images: ["https://images.unsplash.com/photo-1517842645767-c639042777db?w=400"],
    tags: ["notebook", "plain", "practical", "navneet"],
    status: "active",
    featured: false
  },
  {
    name: "Camlin Sketch Book - 50 Pages",
    description: "Professional sketch book with 50 acid-free pages. Perfect for artists and designers. Features thick paper suitable for various media.",
    category: "Notebooks",
    brand: "Camlin",
    price: 150,
    comparePrice: 180,
    sku: "CML-001",
    stock: 200,
    images: ["https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400"],
    tags: ["sketchbook", "plain", "art", "camlin"],
    status: "active",
    featured: true
  },
  {
    name: "Apsara Premium Notebook - 180 Pages",
    description: "Premium quality notebook with 180 ruled pages. Features smooth paper and elegant cover design.",
    category: "Notebooks",
    brand: "Apsara",
    price: 95,
    comparePrice: 120,
    sku: "APS-001",
    stock: 450,
    images: ["https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=400"],
    tags: ["notebook", "ruled", "premium", "apsara"],
    status: "active",
    featured: false
  },
  {
    name: "Reynolds Spiral Notebook - 150 Pages",
    description: "Spiral bound notebook with 150 pages. Easy to flip and write. Features ruled pages and durable cover.",
    category: "Notebooks",
    brand: "Reynolds",
    price: 110,
    comparePrice: 130,
    sku: "REY-001",
    stock: 300,
    images: ["https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=400"],
    tags: ["notebook", "ruled", "spiral", "reynolds"],
    status: "active",
    featured: false
  },
  {
    name: "Faber-Castell Designer Notebook - 120 Pages",
    description: "Designer notebook with premium paper quality. Perfect for creative professionals. Features ruled pages and elegant design.",
    category: "Notebooks",
    brand: "Faber-Castell",
    price: 200,
    comparePrice: 250,
    sku: "FAB-001",
    stock: 150,
    images: ["https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400"],
    tags: ["notebook", "ruled", "premium", "faber-castell"],
    status: "active",
    featured: true
  },
  {
    name: "Staedtler Notebook - 100 Pages",
    description: "German quality notebook with 100 pages. Features premium paper and durable binding.",
    category: "Notebooks",
    brand: "Staedtler",
    price: 180,
    comparePrice: 220,
    sku: "STT-001",
    stock: 120,
    images: ["https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400"],
    tags: ["notebook", "ruled", "premium", "staedtler"],
    status: "active",
    featured: false
  },
  {
    name: "Pilot Executive Notebook - 160 Pages",
    description: "Executive notebook with premium paper. Perfect for business use. Features ruled pages and professional design.",
    category: "Notebooks",
    brand: "Pilot",
    price: 250,
    comparePrice: 300,
    sku: "PIL-001",
    stock: 100,
    images: ["https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=400"],
    tags: ["notebook", "ruled", "executive", "pilot"],
    status: "active",
    featured: true
  },
  {
    name: "Cello Soft Cover Notebook - 140 Pages",
    description: "Soft cover notebook with 140 pages. Features smooth paper and comfortable writing experience.",
    category: "Notebooks",
    brand: "Cello",
    price: 80,
    comparePrice: 95,
    sku: "CEL-001",
    stock: 380,
    images: ["https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=400"],
    tags: ["notebook", "ruled", "soft-cover", "cello"],
    status: "active",
    featured: false
  },
  {
    name: "Luxor Premium Notebook - 200 Pages",
    description: "Premium notebook with 200 pages. Features high-quality paper and elegant cover design.",
    category: "Notebooks",
    brand: "Luxor",
    price: 130,
    comparePrice: 160,
    sku: "LUX-001",
    stock: 280,
    images: ["https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400"],
    tags: ["notebook", "ruled", "premium", "luxor"],
    status: "active",
    featured: false
  },

  // Pens
  {
    name: "Reynolds Jetter Gel Pen - Black",
    description: "Smooth writing gel pen with black ink. Features 0.7mm tip and comfortable grip. Perfect for everyday writing.",
    category: "Pens",
    brand: "Reynolds",
    price: 15,
    comparePrice: 20,
    sku: "REY-PEN-001",
    stock: 1000,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["pen", "gel", "black", "reynolds"],
    status: "active",
    featured: true,
    variants: [
      { type: "Color", value: "Black", price: 15 },
      { type: "Color", value: "Blue", price: 15 },
      { type: "Color", value: "Red", price: 15 }
    ]
  },
  {
    name: "Reynolds Jetter Gel Pen - Blue",
    description: "Smooth writing gel pen with blue ink. Features 0.7mm tip and comfortable grip. Perfect for everyday writing.",
    category: "Pens",
    brand: "Reynolds",
    price: 15,
    comparePrice: 20,
    sku: "REY-PEN-002",
    stock: 950,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["pen", "gel", "blue", "reynolds"],
    status: "active",
    featured: false
  },
  {
    name: "Pilot V5 Hi-Tecpoint Pen",
    description: "Premium quality pen with 0.5mm tip. Features smooth ink flow and comfortable grip. Perfect for precise writing.",
    category: "Pens",
    brand: "Pilot",
    price: 45,
    comparePrice: 55,
    sku: "PIL-PEN-001",
    stock: 500,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["pen", "ballpoint", "premium", "pilot"],
    status: "active",
    featured: true
  },
  {
    name: "Pilot V7 Hi-Tecpoint Pen",
    description: "Premium quality pen with 0.7mm tip. Features smooth ink flow and comfortable grip. Perfect for everyday writing.",
    category: "Pens",
    brand: "Pilot",
    price: 50,
    comparePrice: 60,
    sku: "PIL-PEN-002",
    stock: 450,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["pen", "ballpoint", "premium", "pilot"],
    status: "active",
    featured: false
  },
  {
    name: "Cello Gripper Gel Pen",
    description: "Comfortable gel pen with rubber grip. Features smooth writing and long-lasting ink. Perfect for students.",
    category: "Pens",
    brand: "Cello",
    price: 12,
    comparePrice: 15,
    sku: "CEL-PEN-001",
    stock: 1200,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["pen", "gel", "gripper", "cello"],
    status: "active",
    featured: true
  },
  {
    name: "Cello Butterflow Ball Pen",
    description: "Smooth writing ball pen with buttery flow. Features 1.0mm tip and comfortable grip.",
    category: "Pens",
    brand: "Cello",
    price: 10,
    comparePrice: 12,
    sku: "CEL-PEN-002",
    stock: 1500,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["pen", "ballpoint", "butterflow", "cello"],
    status: "active",
    featured: false
  },
  {
    name: "Faber-Castell Grip 2011 Pen",
    description: "Ergonomic pen with comfortable grip. Features smooth writing and premium quality. Perfect for long writing sessions.",
    category: "Pens",
    brand: "Faber-Castell",
    price: 35,
    comparePrice: 45,
    sku: "FAB-PEN-001",
    stock: 400,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["pen", "ballpoint", "ergonomic", "faber-castell"],
    status: "active",
    featured: true
  },
  {
    name: "Faber-Castell E-Motion Pen",
    description: "Premium pen with elegant design. Features smooth writing and comfortable grip. Perfect for professionals.",
    category: "Pens",
    brand: "Faber-Castell",
    price: 250,
    comparePrice: 300,
    sku: "FAB-PEN-002",
    stock: 100,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["pen", "ballpoint", "premium", "faber-castell"],
    status: "active",
    featured: false
  },
  {
    name: "Staedtler Triplus Fineliner",
    description: "Premium fineliner pen with 0.4mm tip. Features ergonomic triangular grip and vibrant colors.",
    category: "Pens",
    brand: "Staedtler",
    price: 55,
    comparePrice: 65,
    sku: "STT-PEN-001",
    stock: 300,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["pen", "fineliner", "premium", "staedtler"],
    status: "active",
    featured: true
  },
  {
    name: "Staedtler LUMOCOLOR Permanent",
    description: "Permanent marker pen with 0.8mm tip. Features water-resistant ink and long-lasting performance.",
    category: "Pens",
    brand: "Staedtler",
    price: 40,
    comparePrice: 50,
    sku: "STT-PEN-002",
    stock: 350,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["pen", "marker", "permanent", "staedtler"],
    status: "active",
    featured: false
  },
  {
    name: "Luxor Icon Ball Pen",
    description: "Stylish ball pen with premium finish. Features smooth writing and comfortable grip.",
    category: "Pens",
    brand: "Luxor",
    price: 25,
    comparePrice: 30,
    sku: "LUX-PEN-001",
    stock: 600,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["pen", "ballpoint", "icon", "luxor"],
    status: "active",
    featured: false
  },
  {
    name: "Luxor Executive Pen Set",
    description: "Premium pen set with 3 pens. Includes ball pen, gel pen, and fountain pen. Perfect for professionals.",
    category: "Pens",
    brand: "Luxor",
    price: 450,
    comparePrice: 550,
    sku: "LUX-PEN-002",
    stock: 50,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["pen", "set", "executive", "luxor"],
    status: "active",
    featured: true
  },

  // Pencils
  {
    name: "Apsara HB Pencil - Pack of 12",
    description: "Premium quality HB pencils. Features smooth graphite and durable wood. Perfect for writing and drawing.",
    category: "Pencils",
    brand: "Apsara",
    price: 60,
    comparePrice: 75,
    sku: "APS-PEN-001",
    stock: 800,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["pencil", "HB", "pack", "apsara"],
    status: "active",
    featured: true
  },
  {
    name: "Apsara 2B Pencil - Pack of 12",
    description: "Soft 2B pencils for drawing. Features smooth graphite and easy sharpening. Perfect for artists.",
    category: "Pencils",
    brand: "Apsara",
    price: 65,
    comparePrice: 80,
    sku: "APS-PEN-002",
    stock: 700,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["pencil", "2B", "pack", "apsara"],
    status: "active",
    featured: false
  },
  {
    name: "Camlin Drawing Pencils - Pack of 6",
    description: "Professional drawing pencils set. Includes 6B, 4B, 2B, HB, H, 2H. Perfect for artists and designers.",
    category: "Pencils",
    brand: "Camlin",
    price: 85,
    comparePrice: 100,
    sku: "CML-PEN-001",
    stock: 400,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["pencil", "drawing", "set", "camlin"],
    status: "active",
    featured: true
  },
  {
    name: "Camlin Sketching Pencils - Pack of 12",
    description: "Complete sketching pencil set. Includes various grades from 6B to 4H. Perfect for detailed artwork.",
    category: "Pencils",
    brand: "Camlin",
    price: 150,
    comparePrice: 180,
    sku: "CML-PEN-002",
    stock: 250,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["pencil", "sketching", "set", "camlin"],
    status: "active",
    featured: false
  },
  {
    name: "Faber-Castell 9000 Pencil - Pack of 12",
    description: "Premium quality pencils from Faber-Castell. Features super-bonded lead and break-resistant design.",
    category: "Pencils",
    brand: "Faber-Castell",
    price: 120,
    comparePrice: 150,
    sku: "FAB-PEN-001",
    stock: 300,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["pencil", "HB", "premium", "faber-castell"],
    status: "active",
    featured: true
  },
  {
    name: "Staedtler Mars Lumograph Pencil",
    description: "Professional drawing pencil. Features high-quality graphite and smooth writing. Perfect for artists.",
    category: "Pencils",
    brand: "Staedtler",
    price: 25,
    comparePrice: 30,
    sku: "STT-PEN-001",
    stock: 500,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["pencil", "drawing", "professional", "staedtler"],
    status: "active",
    featured: false
  },
  {
    name: "Nataraj Pencil - Pack of 12",
    description: "Budget-friendly HB pencils. Features smooth writing and durable wood. Perfect for students.",
    category: "Pencils",
    brand: "Nataraj",
    price: 45,
    comparePrice: 55,
    sku: "NAT-PEN-001",
    stock: 1000,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["pencil", "HB", "budget", "nataraj"],
    status: "active",
    featured: true
  },
  {
    name: "Doms Pencil - Pack of 12",
    description: "Quality pencils at affordable price. Features smooth graphite and easy sharpening.",
    category: "Pencils",
    brand: "Doms",
    price: 40,
    comparePrice: 50,
    sku: "DOM-PEN-001",
    stock: 900,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["pencil", "HB", "budget", "doms"],
    status: "active",
    featured: false
  },

  // Erasers
  {
    name: "Apsara Non-Dust Eraser - Pack of 3",
    description: "Premium non-dust eraser. Features clean erasing and minimal residue. Perfect for students.",
    category: "Erasers",
    brand: "Apsara",
    price: 30,
    comparePrice: 40,
    sku: "APS-ERA-001",
    stock: 600,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["eraser", "non-dust", "pack", "apsara"],
    status: "active",
    featured: true
  },
  {
    name: "Camlin Soft Eraser - Pack of 5",
    description: "Soft eraser for clean erasing. Features gentle on paper and effective performance.",
    category: "Erasers",
    brand: "Camlin",
    price: 35,
    comparePrice: 45,
    sku: "CML-ERA-001",
    stock: 550,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["eraser", "soft", "pack", "camlin"],
    status: "active",
    featured: false
  },
  {
    name: "Faber-Castell Dust-Free Eraser",
    description: "Premium dust-free eraser. Features clean erasing and long-lasting performance.",
    category: "Erasers",
    brand: "Faber-Castell",
    price: 25,
    comparePrice: 30,
    sku: "FAB-ERA-001",
    stock: 400,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["eraser", "dust-free", "premium", "faber-castell"],
    status: "active",
    featured: true
  },
  {
    name: "Staedtler Mars Plastic Eraser",
    description: "Professional quality eraser. Features clean erasing and minimal residue. Perfect for artists.",
    category: "Erasers",
    brand: "Staedtler",
    price: 30,
    comparePrice: 35,
    sku: "STT-ERA-001",
    stock: 350,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["eraser", "plastic", "professional", "staedtler"],
    status: "active",
    featured: false
  },
  {
    name: "Nataraj Eraser - Pack of 10",
    description: "Budget-friendly erasers. Features effective erasing and good value for money.",
    category: "Erasers",
    brand: "Nataraj",
    price: 40,
    comparePrice: 50,
    sku: "NAT-ERA-001",
    stock: 800,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["eraser", "budget", "pack", "nataraj"],
    status: "active",
    featured: false
  },

  // Sharpeners
  {
    name: "Apsara Sharpener - Single",
    description: "Compact pencil sharpener. Features sharp blade and durable design. Perfect for students.",
    category: "Sharpeners",
    brand: "Apsara",
    price: 15,
    comparePrice: 20,
    sku: "APS-SHP-001",
    stock: 1000,
    images: ["https://images.unsplash.com/photo-1635350649447-3f895a9ef47e?w=400"],
    tags: ["sharpener", "single", "apsara"],
    status: "active",
    featured: true
  },
  {
    name: "Camlin Metal Sharpener",
    description: "Durable metal sharpener. Features sharp blade and long-lasting performance.",
    category: "Sharpeners",
    brand: "Camlin",
    price: 25,
    comparePrice: 30,
    sku: "CML-SHP-001",
    stock: 600,
    images: ["https://images.unsplash.com/photo-1635350649447-3f895a9ef47e?w=400"],
    tags: ["sharpener", "metal", "camlin"],
    status: "active",
    featured: false
  },
  {
    name: "Faber-Castell Grip Sharpener",
    description: "Ergonomic sharpener with grip. Features sharp blade and comfortable design.",
    category: "Sharpeners",
    brand: "Faber-Castell",
    price: 35,
    comparePrice: 45,
    sku: "FAB-SHP-001",
    stock: 400,
    images: ["https://images.unsplash.com/photo-1635350649447-3f895a9ef47e?w=400"],
    tags: ["sharpener", "grip", "faber-castell"],
    status: "active",
    featured: true
  },
  {
    name: "Staedtler Double-Hole Sharpener",
    description: "Double-hole sharpener for different pencil sizes. Features sharp blades and durable design.",
    category: "Sharpeners",
    brand: "Staedtler",
    price: 40,
    comparePrice: 50,
    sku: "STT-SHP-001",
    stock: 350,
    images: ["https://images.unsplash.com/photo-1635350649447-3f895a9ef47e?w=400"],
    tags: ["sharpener", "double-hole", "staedtler"],
    status: "active",
    featured: false
  },
  {
    name: "Nataraj Sharpener - Pack of 5",
    description: "Budget-friendly sharpeners. Features sharp blades and good value for money.",
    category: "Sharpeners",
    brand: "Nataraj",
    price: 35,
    comparePrice: 45,
    sku: "NAT-SHP-001",
    stock: 700,
    images: ["https://images.unsplash.com/photo-1635350649447-3f895a9ef47e?w=400"],
    tags: ["sharpener", "pack", "budget", "nataraj"],
    status: "active",
    featured: false
  },

  // Geometry Box
  {
    name: "Classmate Geometry Box - 15 Pieces",
    description: "Complete geometry box with 15 pieces. Includes compass, divider, protractor, set squares, and more.",
    category: "Geometry Box",
    brand: "Classmate",
    price: 250,
    comparePrice: 300,
    sku: "CLM-GEOM-001",
    stock: 400,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["geometry", "box", "15-pieces", "classmate"],
    status: "active",
    featured: true
  },
  {
    name: "Navneet Geometry Box - 12 Pieces",
    description: "Complete geometry box with 12 pieces. Includes all essential tools for students.",
    category: "Geometry Box",
    brand: "Navneet",
    price: 180,
    comparePrice: 220,
    sku: "NAV-GEOM-001",
    stock: 500,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["geometry", "box", "12-pieces", "navneet"],
    status: "active",
    featured: false
  },
  {
    name: "Camlin Geometry Box - 14 Pieces",
    description: "Professional geometry box with 14 pieces. Features high-quality tools and durable case.",
    category: "Geometry Box",
    brand: "Camlin",
    price: 220,
    comparePrice: 270,
    sku: "CML-GEOM-001",
    stock: 350,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["geometry", "box", "14-pieces", "camlin"],
    status: "active",
    featured: true
  },
  {
    name: "Faber-Castell Geometry Set",
    description: "Premium geometry set with precision tools. Perfect for engineering students and professionals.",
    category: "Geometry Box",
    brand: "Faber-Castell",
    price: 350,
    comparePrice: 420,
    sku: "FAB-GEOM-001",
    stock: 200,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["geometry", "set", "premium", "faber-castell"],
    status: "active",
    featured: false
  },
  {
    name: "Staedtler Geometry Box",
    description: "German quality geometry box. Features precision tools and durable case.",
    category: "Geometry Box",
    brand: "Staedtler",
    price: 400,
    comparePrice: 480,
    sku: "STT-GEOM-001",
    stock: 150,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["geometry", "box", "premium", "staedtler"],
    status: "active",
    featured: true
  },

  // Art Supplies
  {
    name: "Camlin Water Color Tubes - 12 Shades",
    description: "Premium water color tubes with 12 shades. Features vibrant colors and smooth application.",
    category: "Art Supplies",
    brand: "Camlin",
    price: 180,
    comparePrice: 220,
    sku: "CML-ART-001",
    stock: 300,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["watercolor", "tubes", "12-shades", "camlin"],
    status: "active",
    featured: true
  },
  {
    name: "Camlin Oil Pastels - 24 Shades",
    description: "Vibrant oil pastels with 24 shades. Features smooth application and rich colors.",
    category: "Art Supplies",
    brand: "Camlin",
    price: 150,
    comparePrice: 180,
    sku: "CML-ART-002",
    stock: 350,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["pastels", "oil", "24-shades", "camlin"],
    status: "active",
    featured: false
  },
  {
    name: "Faber-Castell Connector Pen Set - 24 Colors",
    description: "Connector pen set with 24 vibrant colors. Features washable ink and ergonomic design.",
    category: "Art Supplies",
    brand: "Faber-Castell",
    price: 350,
    comparePrice: 420,
    sku: "FAB-ART-001",
    stock: 200,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["pens", "connector", "24-colors", "faber-castell"],
    status: "active",
    featured: true
  },
  {
    name: "Faber-Castell Albrecht Durer Watercolor Pencils",
    description: "Professional watercolor pencils. Features high-quality pigments and excellent lightfastness.",
    category: "Art Supplies",
    brand: "Faber-Castell",
    price: 800,
    comparePrice: 950,
    sku: "FAB-ART-002",
    stock: 80,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["pencils", "watercolor", "professional", "faber-castell"],
    status: "active",
    featured: false
  },
  {
    name: "Staedtler Noris Club Colored Pencils - 24 Colors",
    description: "Quality colored pencils with 24 vibrant colors. Features smooth application and break-resistant leads.",
    category: "Art Supplies",
    brand: "Staedtler",
    price: 280,
    comparePrice: 340,
    sku: "STT-ART-001",
    stock: 250,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["pencils", "colored", "24-colors", "staedtler"],
    status: "active",
    featured: true
  },
  {
    name: "Camlin Brush Set - 12 Pieces",
    description: "Complete brush set with 12 brushes. Includes various sizes for different techniques.",
    category: "Art Supplies",
    brand: "Camlin",
    price: 200,
    comparePrice: 250,
    sku: "CML-ART-003",
    stock: 300,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["brushes", "set", "12-pieces", "camlin"],
    status: "active",
    featured: false
  },

  // Files & Folders
  {
    name: "Classmate Spiral Binder - 300 Pages",
    description: "Spiral binder with 300 pages. Features durable cover and smooth paper. Perfect for projects.",
    category: "Files & Folders",
    brand: "Classmate",
    price: 180,
    comparePrice: 220,
    sku: "CLM-FILE-001",
    stock: 400,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["binder", "spiral", "300-pages", "classmate"],
    status: "active",
    featured: true
  },
  {
    name: "Navneet File Folder - A4 Size",
    description: "Durable file folder for A4 documents. Features plastic cover and secure closure.",
    category: "Files & Folders",
    brand: "Navneet",
    price: 45,
    comparePrice: 55,
    sku: "NAV-FILE-001",
    stock: 600,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["folder", "A4", "plastic", "navneet"],
    status: "active",
    featured: false
  },
  {
    name: "Camlin Display File - 40 Pockets",
    description: "Display file with 40 pockets. Perfect for organizing documents and presentations.",
    category: "Files & Folders",
    brand: "Camlin",
    price: 120,
    comparePrice: 150,
    sku: "CML-FILE-001",
    stock: 350,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["file", "display", "40-pockets", "camlin"],
    status: "active",
    featured: true
  },
  {
    name: "Faber-Castell Ring Binder - 2 Inch",
    description: "Premium ring binder with 2-inch rings. Features durable cover and smooth mechanism.",
    category: "Files & Folders",
    brand: "Faber-Castell",
    price: 150,
    comparePrice: 180,
    sku: "FAB-FILE-001",
    stock: 250,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["binder", "ring", "2-inch", "faber-castell"],
    status: "active",
    featured: false
  },
  {
    name: "Staedtler File Organizer",
    description: "Professional file organizer. Features multiple compartments and sturdy construction.",
    category: "Files & Folders",
    brand: "Staedtler",
    price: 350,
    comparePrice: 420,
    sku: "STT-FILE-001",
    stock: 150,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["organizer", "file", "professional", "staedtler"],
    status: "active",
    featured: true
  },

  // Diaries
  {
    name: "Classmate Executive Diary 2024",
    description: "Premium executive diary for 2024. Features daily pages, notes section, and elegant cover.",
    category: "Diaries",
    brand: "Classmate",
    price: 350,
    comparePrice: 420,
    sku: "CLM-DIA-001",
    stock: 200,
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400"],
    tags: ["diary", "executive", "2024", "classmate"],
    status: "active",
    featured: true
  },
  {
    name: "Navneet Daily Planner 2024",
    description: "Daily planner for 2024. Features hourly slots, to-do lists, and motivational quotes.",
    category: "Diaries",
    brand: "Navneet",
    price: 280,
    comparePrice: 340,
    sku: "NAV-DIA-001",
    stock: 300,
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400"],
    tags: ["planner", "daily", "2024", "navneet"],
    status: "active",
    featured: false
  },
  {
    name: "Camlin Art Diary - 100 Pages",
    description: "Art diary with 100 pages. Features thick paper suitable for various media.",
    category: "Diaries",
    brand: "Camlin",
    price: 200,
    comparePrice: 250,
    sku: "CML-DIA-001",
    stock: 250,
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400"],
    tags: ["diary", "art", "100-pages", "camlin"],
    status: "active",
    featured: true
  },
  {
    name: "Faber-Castell Premium Diary",
    description: "Premium leather diary with elegant design. Features high-quality paper and bookmark ribbon.",
    category: "Diaries",
    brand: "Faber-Castell",
    price: 500,
    comparePrice: 600,
    sku: "FAB-DIA-001",
    stock: 100,
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400"],
    tags: ["diary", "premium", "leather", "faber-castell"],
    status: "active",
    featured: false
  },
  {
    name: "Staedtler Business Planner",
    description: "Professional business planner. Features monthly calendars, notes sections, and contact pages.",
    category: "Diaries",
    brand: "Staedtler",
    price: 320,
    comparePrice: 380,
    sku: "STT-DIA-001",
    stock: 180,
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400"],
    tags: ["planner", "business", "professional", "staedtler"],
    status: "active",
    featured: true
  },

  // Calculators
  {
    name: "Casio Scientific Calculator FX-991EX",
    description: "Advanced scientific calculator with 552 functions. Features natural textbook display and solar power.",
    category: "Calculator",
    brand: "Casio",
    price: 1200,
    comparePrice: 1450,
    sku: "CAS-CAL-001",
    stock: 150,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["calculator", "scientific", "casio"],
    status: "active",
    featured: true
  },
  {
    name: "Casio Basic Calculator",
    description: "Basic calculator for everyday use. Features large display and solar power.",
    category: "Calculator",
    brand: "Casio",
    price: 350,
    comparePrice: 420,
    sku: "CAS-CAL-002",
    stock: 300,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["calculator", "basic", "casio"],
    status: "active",
    featured: false
  },
  {
    name: "Orpat Scientific Calculator",
    description: "Budget-friendly scientific calculator. Features 240 functions and dual power.",
    category: "Calculator",
    brand: "Orpat",
    price: 450,
    comparePrice: 550,
    sku: "ORP-CAL-001",
    stock: 250,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["calculator", "scientific", "budget", "orpat"],
    status: "active",
    featured: true
  },
  {
    name: "Texas Instruments Graphing Calculator",
    description: "Professional graphing calculator. Features advanced functions and large display.",
    category: "Calculator",
    brand: "Texas Instruments",
    price: 8500,
    comparePrice: 10000,
    sku: "TI-CAL-001",
    stock: 50,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["calculator", "graphing", "professional", "texas-instruments"],
    status: "active",
    featured: false
  },
  {
    name: "Canon Printing Calculator",
    description: "Printing calculator for business use. Features fast printing and large display.",
    category: "Calculator",
    brand: "Canon",
    price: 2500,
    comparePrice: 3000,
    sku: "CAN-CAL-001",
    stock: 80,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["calculator", "printing", "business", "canon"],
    status: "active",
    featured: true
  },

  // School Bags
  {
    name: "Skybags School Backpack - Blue",
    description: "Stylish school backpack with multiple compartments. Features ergonomic design and water-resistant material.",
    category: "School Bags",
    brand: "Skybags",
    price: 1200,
    comparePrice: 1450,
    sku: "SKY-BAG-001",
    stock: 150,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
    tags: ["backpack", "school", "blue", "skybags"],
    status: "active",
    featured: true,
    variants: [
      { type: "Color", value: "Blue", price: 1200 },
      { type: "Color", value: "Red", price: 1200 },
      { type: "Color", value: "Black", price: 1200 }
    ]
  },
  {
    name: "Wildcraft School Backpack - Black",
    description: "Durable school backpack with padded straps. Features laptop compartment and anti-theft pocket.",
    category: "School Bags",
    brand: "Wildcraft",
    price: 1500,
    comparePrice: 1800,
    sku: "WLD-BAG-001",
    stock: 120,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
    tags: ["backpack", "school", "black", "wildcraft"],
    status: "active",
    featured: false
  },
  {
    name: "American Tourister School Bag",
    description: "Premium school bag with trolley system. Features spacious compartments and sturdy wheels.",
    category: "School Bags",
    brand: "American Tourister",
    price: 2500,
    comparePrice: 3000,
    sku: "AMT-BAG-001",
    stock: 80,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
    tags: ["bag", "school", "trolley", "american-tourister"],
    status: "active",
    featured: true
  },
  {
    name: "Puma School Backpack - Grey",
    description: "Sporty school backpack with modern design. Features multiple pockets and comfortable straps.",
    category: "School Bags",
    brand: "Puma",
    price: 1800,
    comparePrice: 2150,
    sku: "PUM-BAG-001",
    stock: 100,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
    tags: ["backpack", "school", "grey", "puma"],
    status: "active",
    featured: false
  },
  {
    name: "Nike School Backpack - Red",
    description: "Stylish Nike backpack for school. Features iconic design and durable construction.",
    category: "School Bags",
    brand: "Nike",
    price: 2200,
    comparePrice: 2600,
    sku: "NIK-BAG-001",
    stock: 90,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
    tags: ["backpack", "school", "red", "nike"],
    status: "active",
    featured: true
  },

  // Water Bottles
  {
    name: "Milton Copper Bottle - 1000ml",
    description: "Pure copper water bottle with 1000ml capacity. Features leak-proof design and health benefits.",
    category: "Water Bottles",
    brand: "Milton",
    price: 450,
    comparePrice: 550,
    sku: "MIL-BOT-001",
    stock: 300,
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400"],
    tags: ["bottle", "copper", "1000ml", "milton"],
    status: "active",
    featured: true
  },
  {
    name: "Milton Steel Bottle - 750ml",
    description: "Stainless steel water bottle with 750ml capacity. Features double-wall insulation.",
    category: "Water Bottles",
    brand: "Milton",
    price: 350,
    comparePrice: 420,
    sku: "MIL-BOT-002",
    stock: 400,
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400"],
    tags: ["bottle", "steel", "750ml", "milton"],
    status: "active",
    featured: false
  },
  {
    name: "Cello Thermo Flask - 1000ml",
    description: "Insulated thermos flask with 1000ml capacity. Keeps liquids hot or cold for 24 hours.",
    category: "Water Bottles",
    brand: "Cello",
    price: 550,
    comparePrice: 650,
    sku: "CEL-BOT-001",
    stock: 250,
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400"],
    tags: ["flask", "thermo", "1000ml", "cello"],
    status: "active",
    featured: true
  },
  {
    name: "Puma Sports Bottle - 750ml",
    description: "Sports water bottle with 750ml capacity. Features easy-sip lid and durable construction.",
    category: "Water Bottles",
    brand: "Puma",
    price: 450,
    comparePrice: 540,
    sku: "PUM-BOT-001",
    stock: 200,
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400"],
    tags: ["bottle", "sports", "750ml", "puma"],
    status: "active",
    featured: false
  },
  {
    name: "Nike Sipper Bottle - 500ml",
    description: "Compact sipper bottle with 500ml capacity. Features flip-top lid and easy carry design.",
    category: "Water Bottles",
    brand: "Nike",
    price: 350,
    comparePrice: 420,
    sku: "NIK-BOT-001",
    stock: 250,
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400"],
    tags: ["bottle", "sipper", "500ml", "nike"],
    status: "active",
    featured: true
  },

  // Craft Supplies
  {
    name: "Camlin Craft Scissors",
    description: "Sharp craft scissors for precision cutting. Features comfortable grip and stainless steel blades.",
    category: "Craft Supplies",
    brand: "Camlin",
    price: 85,
    comparePrice: 100,
    sku: "CML-CRF-001",
    stock: 400,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["scissors", "craft", "camlin"],
    status: "active",
    featured: true
  },
  {
    name: "Faber-Castell Glue Stick",
    description: "Strong glue stick for craft projects. Features easy application and quick drying.",
    category: "Craft Supplies",
    brand: "Faber-Castell",
    price: 35,
    comparePrice: 45,
    sku: "FAB-CRF-001",
    stock: 600,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["glue", "stick", "faber-castell"],
    status: "active",
    featured: false
  },
  {
    name: "Staedtler Craft Knife",
    description: "Precision craft knife with retractable blade. Perfect for detailed cutting work.",
    category: "Craft Supplies",
    brand: "Staedtler",
    price: 55,
    comparePrice: 65,
    sku: "STT-CRF-001",
    stock: 350,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["knife", "craft", "staedtler"],
    status: "active",
    featured: true
  },
  {
    name: "Camlin Fevicol Tube - 100g",
    description: "Strong adhesive glue for crafts. Features quick bonding and durable hold.",
    category: "Craft Supplies",
    brand: "Camlin",
    price: 45,
    comparePrice: 55,
    sku: "CML-CRF-002",
    stock: 500,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["glue", "fevicol", "camlin"],
    status: "active",
    featured: false
  },
  {
    name: "Faber-Castell Ruler Set",
    description: "Complete ruler set with various sizes. Features accurate measurements and durable construction.",
    category: "Craft Supplies",
    brand: "Faber-Castell",
    price: 75,
    comparePrice: 90,
    sku: "FAB-CRF-002",
    stock: 450,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["ruler", "set", "faber-castell"],
    status: "active",
    featured: true
  },

  // Additional products to reach 140+
  {
    name: "Classmate Spiral Notebook - 300 Pages",
    description: "Spiral notebook with 300 pages. Features durable binding and smooth paper.",
    category: "Notebooks",
    brand: "Classmate",
    price: 160,
    comparePrice: 190,
    sku: "CLM-003",
    stock: 350,
    images: ["https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=400"],
    tags: ["notebook", "spiral", "300-pages", "classmate"],
    status: "active",
    featured: false
  },
  {
    name: "Navneet Unruled Notebook - 100 Pages",
    description: "Unruled notebook for drawing and notes. Features smooth paper and durable cover.",
    category: "Notebooks",
    brand: "Navneet",
    price: 45,
    comparePrice: 55,
    sku: "NAV-003",
    stock: 500,
    images: ["https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400"],
    tags: ["notebook", "unruled", "navneet"],
    status: "active",
    featured: false
  },
  {
    name: "Reynolds Ball Pen - Pack of 10",
    description: "Pack of 10 ball pens. Features smooth writing and long-lasting ink.",
    category: "Pens",
    brand: "Reynolds",
    price: 80,
    comparePrice: 100,
    sku: "REY-PEN-003",
    stock: 800,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["pen", "ballpoint", "pack", "reynolds"],
    status: "active",
    featured: false
  },
  {
    name: "Pilot Vball Grip Pen",
    description: "Comfortable ball pen with grip. Features smooth ink flow and ergonomic design.",
    category: "Pens",
    brand: "Pilot",
    price: 35,
    comparePrice: 42,
    sku: "PIL-PEN-003",
    stock: 600,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["pen", "ballpoint", "grip", "pilot"],
    status: "active",
    featured: false
  },
  {
    name: "Cello Maxwriter Ball Pen",
    description: "Premium ball pen with smooth writing. Features comfortable grip and long-lasting ink.",
    category: "Pens",
    brand: "Cello",
    price: 18,
    comparePrice: 22,
    sku: "CEL-PEN-003",
    stock: 1100,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["pen", "ballpoint", "maxwriter", "cello"],
    status: "active",
    featured: false
  },
  {
    name: "Faber-Castell Textliner 46 Pastel",
    description: "Pastel highlighter set with 6 colors. Features chisel tip and gentle highlighting.",
    category: "Pens",
    brand: "Faber-Castell",
    price: 180,
    comparePrice: 220,
    sku: "FAB-PEN-003",
    stock: 250,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["highlighter", "pastel", "set", "faber-castell"],
    status: "active",
    featured: true
  },
  {
    name: "Staedtler Textsurfer Classic",
    description: "Classic highlighter with chisel tip. Features vibrant colors and long-lasting ink.",
    category: "Pens",
    brand: "Staedtler",
    price: 25,
    comparePrice: 30,
    sku: "STT-PEN-003",
    stock: 700,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["highlighter", "classic", "staedtler"],
    status: "active",
    featured: false
  },
  {
    name: "Luxor Highlighter - Pack of 5",
    description: "Pack of 5 highlighters in assorted colors. Features chisel tip and quick-drying ink.",
    category: "Pens",
    brand: "Luxor",
    price: 75,
    comparePrice: 90,
    sku: "LUX-PEN-003",
    stock: 500,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["highlighter", "pack", "luxor"],
    status: "active",
    featured: false
  },
  {
    name: "Apsara Graphite Pencil - Pack of 10",
    description: "Graphite pencils for sketching. Features smooth lead and easy sharpening.",
    category: "Pencils",
    brand: "Apsara",
    price: 50,
    comparePrice: 60,
    sku: "APS-PEN-003",
    stock: 700,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["pencil", "graphite", "pack", "apsara"],
    status: "active",
    featured: false
  },
  {
    name: "Camlin Mechanical Pencil 0.5mm",
    description: "Mechanical pencil with 0.5mm lead. Features comfortable grip and lead refill.",
    category: "Pencils",
    brand: "Camlin",
    price: 45,
    comparePrice: 55,
    sku: "CML-PEN-003",
    stock: 550,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["pencil", "mechanical", "camlin"],
    status: "active",
    featured: true
  },
  {
    name: "Faber-Castell Mechanical Pencil 0.7mm",
    description: "Premium mechanical pencil with 0.7mm lead. Features ergonomic grip and lead indicator.",
    category: "Pencils",
    brand: "Faber-Castell",
    price: 85,
    comparePrice: 100,
    sku: "FAB-PEN-003",
    stock: 300,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["pencil", "mechanical", "faber-castell"],
    status: "active",
    featured: false
  },
  {
    name: "Staedtler Mars Micro Mechanical Pencil",
    description: "Precision mechanical pencil with 0.5mm lead. Features compact design and lead refill.",
    category: "Pencils",
    brand: "Staedtler",
    price: 120,
    comparePrice: 145,
    sku: "STT-PEN-003",
    stock: 250,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["pencil", "mechanical", "staedtler"],
    status: "active",
    featured: true
  },
  {
    name: "Nataraj Mechanical Pencil",
    description: "Budget-friendly mechanical pencil. Features 0.5mm lead and comfortable grip.",
    category: "Pencils",
    brand: "Nataraj",
    price: 25,
    comparePrice: 30,
    sku: "NAT-PEN-003",
    stock: 900,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["pencil", "mechanical", "budget", "nataraj"],
    status: "active",
    featured: false
  },
  {
    name: "Apsara Art Eraser - Large",
    description: "Large art eraser for detailed work. Features clean erasing and minimal residue.",
    category: "Erasers",
    brand: "Apsara",
    price: 20,
    comparePrice: 25,
    sku: "APS-ERA-003",
    stock: 600,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["eraser", "art", "large", "apsara"],
    status: "active",
    featured: false
  },
  {
    name: "Camlin Kneadable Eraser",
    description: "Kneadable eraser for charcoal and pastel. Features moldable design and gentle cleaning.",
    category: "Erasers",
    brand: "Camlin",
    price: 35,
    comparePrice: 42,
    sku: "CML-ERA-003",
    stock: 400,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["eraser", "kneadable", "camlin"],
    status: "active",
    featured: true
  },
  {
    name: "Faber-Castell PVC-Free Eraser",
    description: "Eco-friendly eraser without PVC. Features clean erasing and sustainable materials.",
    category: "Erasers",
    brand: "Faber-Castell",
    price: 30,
    comparePrice: 35,
    sku: "FAB-ERA-003",
    stock: 450,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["eraser", "pvc-free", "eco", "faber-castell"],
    status: "active",
    featured: false
  },
  {
    name: "Staedtler Rasoplast Eraser",
    description: "Quality plastic eraser. Features clean erasing and long-lasting performance.",
    category: "Erasers",
    brand: "Staedtler",
    price: 20,
    comparePrice: 25,
    sku: "STT-ERA-003",
    stock: 550,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["eraser", "plastic", "staedtler"],
    status: "active",
    featured: false
  },
  {
    name: "Nataraj Dustless Eraser - Pack of 10",
    description: "Pack of 10 dustless erasers. Features clean erasing and minimal residue.",
    category: "Erasers",
    brand: "Nataraj",
    price: 50,
    comparePrice: 60,
    sku: "NAT-ERA-003",
    stock: 700,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["eraser", "dustless", "pack", "nataraj"],
    status: "active",
    featured: false
  },
  {
    name: "Apsara Battery Sharpener",
    description: "Battery-operated pencil sharpener. Features automatic sharpening and durable blades.",
    category: "Sharpeners",
    brand: "Apsara",
    price: 250,
    comparePrice: 300,
    sku: "APS-SHP-003",
    stock: 200,
    images: ["https://images.unsplash.com/photo-1635350649447-3f895a9ef47e?w=400"],
    tags: ["sharpener", "battery", "apsara"],
    status: "active",
    featured: true
  },
  {
    name: "Camlin Electric Sharpener",
    description: "Electric pencil sharpener with helical blades. Features fast sharpening and large shavings container.",
    category: "Sharpeners",
    brand: "Camlin",
    price: 450,
    comparePrice: 550,
    sku: "CML-SHP-003",
    stock: 150,
    images: ["https://images.unsplash.com/photo-1635350649447-3f895a9ef47e?w=400"],
    tags: ["sharpener", "electric", "camlin"],
    status: "active",
    featured: false
  },
  {
    name: "Faber-Castell Canister Sharpener",
    description: "Canister sharpener with container. Features sharp blades and easy cleaning.",
    category: "Sharpeners",
    brand: "Faber-Castell",
    price: 35,
    comparePrice: 42,
    sku: "FAB-SHP-003",
    stock: 400,
    images: ["https://images.unsplash.com/photo-1635350649447-3f895a9ef47e?w=400"],
    tags: ["sharpener", "canister", "faber-castell"],
    status: "active",
    featured: false
  },
  {
    name: "Staedtler Tub Sharpener",
    description: "Tub sharpener with container. Features sharp blades and compact design.",
    category: "Sharpeners",
    brand: "Staedtler",
    price: 25,
    comparePrice: 30,
    sku: "STT-SHP-003",
    stock: 500,
    images: ["https://images.unsplash.com/photo-1635350649447-3f895a9ef47e?w=400"],
    tags: ["sharpener", "tub", "staedtler"],
    status: "active",
    featured: false
  },
  {
    name: "Nataraj Plastic Sharpener - Pack of 10",
    description: "Pack of 10 plastic sharpeners. Features sharp blades and budget-friendly price.",
    category: "Sharpeners",
    brand: "Nataraj",
    price: 50,
    comparePrice: 60,
    sku: "NAT-SHP-003",
    stock: 800,
    images: ["https://images.unsplash.com/photo-1635350649447-3f895a9ef47e?w=400"],
    tags: ["sharpener", "plastic", "pack", "nataraj"],
    status: "active",
    featured: false
  },
  {
    name: "Classmate Mini Geometry Box",
    description: "Compact geometry box with essential tools. Perfect for students on the go.",
    category: "Geometry Box",
    brand: "Classmate",
    price: 150,
    comparePrice: 180,
    sku: "CLM-GEOM-003",
    stock: 350,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["geometry", "box", "mini", "classmate"],
    status: "active",
    featured: false
  },
  {
    name: "Navneet Premium Geometry Box",
    description: "Premium geometry box with precision tools. Features metal compass and durable case.",
    category: "Geometry Box",
    brand: "Navneet",
    price: 200,
    comparePrice: 240,
    sku: "NAV-GEOM-003",
    stock: 300,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["geometry", "box", "premium", "navneet"],
    status: "active",
    featured: false
  },
  {
    name: "Camlin Student Geometry Set",
    description: "Student geometry set with basic tools. Perfect for school use.",
    category: "Geometry Box",
    brand: "Camlin",
    price: 120,
    comparePrice: 145,
    sku: "CML-GEOM-003",
    stock: 400,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["geometry", "set", "student", "camlin"],
    status: "active",
    featured: false
  },
  {
    name: "Faber-Castell Compass Set",
    description: "Professional compass set with accessories. Features precision tools and storage case.",
    category: "Geometry Box",
    brand: "Faber-Castell",
    price: 280,
    comparePrice: 340,
    sku: "FAB-GEOM-003",
    stock: 200,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["compass", "set", "professional", "faber-castell"],
    status: "active",
    featured: false
  },
  {
    name: "Staedtler Mars Geometry Set",
    description: "German quality geometry set. Features precision tools and durable case.",
    category: "Geometry Box",
    brand: "Staedtler",
    price: 320,
    comparePrice: 380,
    sku: "STT-GEOM-003",
    stock: 180,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["geometry", "set", "premium", "staedtler"],
    status: "active",
    featured: false
  },
  {
    name: "Camlin Acrylic Colors - 12 Tubes",
    description: "Acrylic paint tubes with 12 colors. Features vibrant pigments and quick drying.",
    category: "Art Supplies",
    brand: "Camlin",
    price: 250,
    comparePrice: 300,
    sku: "CML-ART-004",
    stock: 250,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["acrylic", "tubes", "12-colors", "camlin"],
    status: "active",
    featured: false
  },
  {
    name: "Faber-Castell Polychromos Pencils - 24 Colors",
    description: "Professional colored pencils with 24 colors. Features high-quality pigments and lightfastness.",
    category: "Art Supplies",
    brand: "Faber-Castell",
    price: 1200,
    comparePrice: 1450,
    sku: "FAB-ART-004",
    stock: 80,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["pencils", "colored", "24-colors", "faber-castell"],
    status: "active",
    featured: true
  },
  {
    name: "Staedtler Triplus Textliner",
    description: "Textliner set with 6 colors. Features chisel tip and quick-drying ink.",
    category: "Art Supplies",
    brand: "Staedtler",
    price: 180,
    comparePrice: 220,
    sku: "STT-ART-003",
    stock: 300,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["textliner", "set", "6-colors", "staedtler"],
    status: "active",
    featured: false
  },
  {
    name: "Camlin Canvas Board - A3 Size",
    description: "Canvas board for painting. Features primed surface and sturdy backing.",
    category: "Art Supplies",
    brand: "Camlin",
    price: 120,
    comparePrice: 145,
    sku: "CML-ART-005",
    stock: 200,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["canvas", "board", "A3", "camlin"],
    status: "active",
    featured: false
  },
  {
    name: "Faber-Castell Canvas Pad - A4",
    description: "Canvas pad with 10 sheets. Features primed surface and easy tear-off pages.",
    category: "Art Supplies",
    brand: "Faber-Castell",
    price: 350,
    comparePrice: 420,
    sku: "FAB-ART-005",
    stock: 150,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["canvas", "pad", "A4", "faber-castell"],
    status: "active",
    featured: false
  },
  {
    name: "Staedtler Sketchbook - A5",
    description: "Sketchbook with 50 pages. Features acid-free paper and durable cover.",
    category: "Art Supplies",
    brand: "Staedtler",
    price: 180,
    comparePrice: 220,
    sku: "STT-ART-004",
    stock: 250,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400"],
    tags: ["sketchbook", "A5", "staedtler"],
    status: "active",
    featured: false
  },
  {
    name: "Classmate File Folder - Legal Size",
    description: "File folder for legal size documents. Features plastic cover and secure closure.",
    category: "Files & Folders",
    brand: "Classmate",
    price: 55,
    comparePrice: 65,
    sku: "CLM-FILE-003",
    stock: 500,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["folder", "legal", "plastic", "classmate"],
    status: "active",
    featured: false
  },
  {
    name: "Navneet Ring Binder - 1 Inch",
    description: "Ring binder with 1-inch rings. Features durable cover and smooth mechanism.",
    category: "Files & Folders",
    brand: "Navneet",
    price: 85,
    comparePrice: 100,
    sku: "NAV-FILE-003",
    stock: 400,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["binder", "ring", "1-inch", "navneet"],
    status: "active",
    featured: false
  },
  {
    name: "Camlin Clear File - 20 Pockets",
    description: "Clear file with 20 pockets. Perfect for organizing documents.",
    category: "Files & Folders",
    brand: "Camlin",
    price: 80,
    comparePrice: 95,
    sku: "CML-FILE-003",
    stock: 450,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["file", "clear", "20-pockets", "camlin"],
    status: "active",
    featured: false
  },
  {
    name: "Faber-Castell Document Box",
    description: "Document box for storage. Features sturdy construction and secure lid.",
    category: "Files & Folders",
    brand: "Faber-Castell",
    price: 180,
    comparePrice: 220,
    sku: "FAB-FILE-003",
    stock: 200,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["box", "document", "faber-castell"],
    status: "active",
    featured: false
  },
  {
    name: "Staedtler Expanding File",
    description: "Expanding file with multiple compartments. Perfect for organizing large documents.",
    category: "Files & Folders",
    brand: "Staedtler",
    price: 250,
    comparePrice: 300,
    sku: "STT-FILE-003",
    stock: 180,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["file", "expanding", "staedtler"],
    status: "active",
    featured: false
  },
  {
    name: "Classmate Weekly Planner 2024",
    description: "Weekly planner for 2024. Features weekly layouts and goal tracking.",
    category: "Diaries",
    brand: "Classmate",
    price: 220,
    comparePrice: 265,
    sku: "CLM-DIA-003",
    stock: 250,
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400"],
    tags: ["planner", "weekly", "2024", "classmate"],
    status: "active",
    featured: false
  },
  {
    name: "Navneet Monthly Planner 2024",
    description: "Monthly planner for 2024. Features monthly calendars and notes sections.",
    category: "Diaries",
    brand: "Navneet",
    price: 180,
    comparePrice: 215,
    sku: "NAV-DIA-003",
    stock: 300,
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400"],
    tags: ["planner", "monthly", "2024", "navneet"],
    status: "active",
    featured: false
  },
  {
    name: "Camlin Journal Diary - 200 Pages",
    description: "Journal diary with 200 pages. Features ruled pages and elegant cover.",
    category: "Diaries",
    brand: "Camlin",
    price: 150,
    comparePrice: 180,
    sku: "CML-DIA-003",
    stock: 280,
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400"],
    tags: ["diary", "journal", "200-pages", "camlin"],
    status: "active",
    featured: false
  },
  {
    name: "Faber-Castell Sketch Diary",
    description: "Sketch diary with plain pages. Features thick paper for artwork.",
    category: "Diaries",
    brand: "Faber-Castell",
    price: 280,
    comparePrice: 340,
    sku: "FAB-DIA-003",
    stock: 180,
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400"],
    tags: ["diary", "sketch", "faber-castell"],
    status: "active",
    featured: false
  },
  {
    name: "Staedtler Notebook Diary",
    description: "Notebook diary with ruled pages. Features durable cover and bookmark ribbon.",
    category: "Diaries",
    brand: "Staedtler",
    price: 200,
    comparePrice: 240,
    sku: "STT-DIA-003",
    stock: 220,
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400"],
    tags: ["diary", "notebook", "staedtler"],
    status: "active",
    featured: false
  },
  {
    name: "Casio Financial Calculator",
    description: "Financial calculator for business use. Features tax calculation and currency conversion.",
    category: "Calculator",
    brand: "Casio",
    price: 850,
    comparePrice: 1020,
    sku: "CAS-CAL-003",
    stock: 120,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["calculator", "financial", "casio"],
    status: "active",
    featured: false
  },
  {
    name: "Orpat Desktop Calculator",
    description: "Desktop calculator with large display. Features dual power and large buttons.",
    category: "Calculator",
    brand: "Orpat",
    price: 280,
    comparePrice: 340,
    sku: "ORP-CAL-003",
    stock: 200,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["calculator", "desktop", "orpat"],
    status: "active",
    featured: false
  },
  {
    name: "Texas Instruments Basic Calculator",
    description: "Basic calculator for everyday use. Features solar power and large display.",
    category: "Calculator",
    brand: "Texas Instruments",
    price: 450,
    comparePrice: 540,
    sku: "TI-CAL-003",
    stock: 150,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["calculator", "basic", "texas-instruments"],
    status: "active",
    featured: false
  },
  {
    name: "Canon Pocket Calculator",
    description: "Compact pocket calculator. Features dual power and slim design.",
    category: "Calculator",
    brand: "Canon",
    price: 350,
    comparePrice: 420,
    sku: "CAN-CAL-003",
    stock: 180,
    images: ["https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400"],
    tags: ["calculator", "pocket", "canon"],
    status: "active",
    featured: false
  },
  {
    name: "Skybags Trolley School Bag",
    description: "Trolley school bag with wheels. Features spacious compartments and sturdy handle.",
    category: "School Bags",
    brand: "Skybags",
    price: 2800,
    comparePrice: 3360,
    sku: "SKY-BAG-003",
    stock: 80,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
    tags: ["bag", "trolley", "school", "skybags"],
    status: "active",
    featured: false
  },
  {
    name: "Wildcraft Trekking Backpack",
    description: "Trekking backpack with rain cover. Features multiple compartments and ergonomic design.",
    category: "School Bags",
    brand: "Wildcraft",
    price: 3200,
    comparePrice: 3840,
    sku: "WLD-BAG-003",
    stock: 60,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
    tags: ["backpack", "trekking", "wildcraft"],
    status: "active",
    featured: false
  },
  {
    name: "American Tourister Backpack",
    description: "Premium backpack with laptop compartment. Features anti-theft pocket and USB charging port.",
    category: "School Bags",
    brand: "American Tourister",
    price: 3500,
    comparePrice: 4200,
    sku: "AMT-BAG-003",
    stock: 50,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
    tags: ["backpack", "premium", "american-tourister"],
    status: "active",
    featured: false
  },
  {
    name: "Puma Gym Backpack",
    description: "Sporty backpack for gym and school. Features shoe compartment and wet pocket.",
    category: "School Bags",
    brand: "Puma",
    price: 2000,
    comparePrice: 2400,
    sku: "PUM-BAG-003",
    stock: 80,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
    tags: ["backpack", "gym", "puma"],
    status: "active",
    featured: false
  },
  {
    name: "Nike Drawstring Bag",
    description: "Lightweight drawstring bag. Perfect for gym and casual use.",
    category: "School Bags",
    brand: "Nike",
    price: 800,
    comparePrice: 960,
    sku: "NIK-BAG-003",
    stock: 120,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
    tags: ["bag", "drawstring", "nike"],
    status: "active",
    featured: false
  },
  {
    name: "Milton Thermosteel Bottle - 500ml",
    description: "Thermosteel bottle with 500ml capacity. Keeps liquids hot for 12 hours, cold for 24 hours.",
    category: "Water Bottles",
    brand: "Milton",
    price: 350,
    comparePrice: 420,
    sku: "MIL-BOT-003",
    stock: 350,
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400"],
    tags: ["bottle", "thermosteel", "500ml", "milton"],
    status: "active",
    featured: false
  },
  {
    name: "Cello Insulated Bottle - 1000ml",
    description: "Insulated bottle with 1000ml capacity. Features double-wall insulation and leak-proof lid.",
    category: "Water Bottles",
    brand: "Cello",
    price: 400,
    comparePrice: 480,
    sku: "CEL-BOT-003",
    stock: 300,
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400"],
    tags: ["bottle", "insulated", "1000ml", "cello"],
    status: "active",
    featured: false
  },
  {
    name: "Puma Metal Bottle - 750ml",
    description: "Metal water bottle with 750ml capacity. Features sleek design and durable construction.",
    category: "Water Bottles",
    brand: "Puma",
    price: 550,
    comparePrice: 660,
    sku: "PUM-BOT-003",
    stock: 200,
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400"],
    tags: ["bottle", "metal", "750ml", "puma"],
    status: "active",
    featured: false
  },
  {
    name: "Nike Hydro Flask - 1000ml",
    description: "Premium hydro flask with 1000ml capacity. Features vacuum insulation and wide mouth.",
    category: "Water Bottles",
    brand: "Nike",
    price: 1200,
    comparePrice: 1440,
    sku: "NIK-BOT-003",
    stock: 100,
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400"],
    tags: ["flask", "hydro", "1000ml", "nike"],
    status: "active",
    featured: true
  },
  {
    name: "Camlin Craft Paper - A4 Size",
    description: "Craft paper pack with 50 sheets. Perfect for DIY projects and crafts.",
    category: "Craft Supplies",
    brand: "Camlin",
    price: 120,
    comparePrice: 145,
    sku: "CML-CRF-004",
    stock: 300,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["paper", "craft", "A4", "camlin"],
    status: "active",
    featured: false
  },
  {
    name: "Faber-Castell Colored Paper Pack",
    description: "Colored paper pack with 10 colors. Perfect for crafts and decorations.",
    category: "Craft Supplies",
    brand: "Faber-Castell",
    price: 150,
    comparePrice: 180,
    sku: "FAB-CRF-004",
    stock: 250,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["paper", "colored", "pack", "faber-castell"],
    status: "active",
    featured: false
  },
  {
    name: "Staedtler Craft Mat",
    description: "Self-healing craft mat. Protects surfaces during cutting and crafting.",
    category: "Craft Supplies",
    brand: "Staedtler",
    price: 450,
    comparePrice: 540,
    sku: "STT-CRF-004",
    stock: 150,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["mat", "craft", "staedtler"],
    status: "active",
    featured: false
  },
  {
    name: "Camlin Origami Paper Pack",
    description: "Origami paper pack with 100 sheets. Features various colors and patterns.",
    category: "Craft Supplies",
    brand: "Camlin",
    price: 180,
    comparePrice: 215,
    sku: "CML-CRF-005",
    stock: 200,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["paper", "origami", "pack", "camlin"],
    status: "active",
    featured: false
  },
  {
    name: "Faber-Castell Craft Punch Set",
    description: "Craft punch set with 5 designs. Perfect for paper crafts and decorations.",
    category: "Craft Supplies",
    brand: "Faber-Castell",
    price: 350,
    comparePrice: 420,
    sku: "FAB-CRF-005",
    stock: 180,
    images: ["https://images.unsplash.com/photo-1583468982228-19f19164a392?w=400"],
    tags: ["punch", "craft", "set", "faber-castell"],
    status: "active",
    featured: false
  }
];

module.exports = products;
